/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Main.Conexion;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexg
 */
public class EliminarProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form EliminarProducto
     */
    public EliminarProducto() {
        initComponents();
        borrar.setOpaque(false);
        borrar.setContentAreaFilled(false);
        borrar.setBorderPainted(false);
        llenarTabla();
    }
    public void eliminarTabla(){
        DefaultTableModel modelo_tabla = (DefaultTableModel) this.jTable1.getModel();
        modelo_tabla.setRowCount(0);
    }
public void  llenarTabla (){
    lbl_producto_eliminarq.setVisible(false);
        Properties datos = new Properties();
        String servidor;
        String driver;
        datos.put("user", "u7tuhhfbmthsu53c");
        datos.put("password", "Nw5nMTEHvX2U2r3gVAYj");
        servidor = "jdbc:mysql://bosgnclh26bmxuw456hf-mysql.services.clever-cloud.com:3306/bosgnclh26bmxuw456hf";
        driver = "com.mysql.jdbc.Driver";
        String pd_nombre,pd_descripcion;
        double pd_compra,pd_venta;
        String pd_fecha;
        int cableProducto;
        String cadenasql;
        cadenasql ="Select * from Productos";
        System.out.println(cadenasql);
        ResultSet datos_productos;
        
        DefaultTableModel modelo_tabla = (DefaultTableModel) this.jTable1.getModel();
        
        try {
            Class.forName(driver);
            Connection con = DriverManager.getConnection(servidor, datos);
            if (con != null) {
                System.out.println("Conecto");
                Statement exe = con.createStatement();
                datos_productos= exe.executeQuery(cadenasql);
                while (datos_productos.next()){
                    cableProducto= datos_productos.getInt("pd_clv");
                    pd_nombre= datos_productos.getString("pd_nombre");
                    pd_descripcion= datos_productos.getString("pd_descripcion");
                    pd_compra= datos_productos.getDouble("pd_precio_cmp");
                    pd_venta= datos_productos.getDouble("pd_precio_vnt");
                    pd_fecha= datos_productos.getString("pd_fecha_cmp");
                    Object vector[]={cableProducto, pd_nombre, pd_descripcion, pd_compra, pd_venta,pd_fecha};
                    modelo_tabla.addRow(vector);
                }   
                
                con.close();
            } else {
                System.out.println("No conecto");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            
            Logger.getLogger(Conexion.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        borrar = new javax.swing.JButton();
        lbl_producto_eliminarq = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setForeground(java.awt.Color.lightGray);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Eliminar productos");
        setToolTipText("");
        setAutoscrolls(true);
        setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/imagexxcf_103507.png"))); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        jTable1.setBackground(new java.awt.Color(255, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Descripcion", "Precio de compra", "Precio de venta", "Fecha de registro"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("ID de producto a eliminar: ");

        borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/eliminar.png"))); // NOI18N
        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        lbl_producto_eliminarq.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_producto_eliminarq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_producto_eliminarq.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(borrar)
                .addContainerGap(738, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_producto_eliminarq, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_producto_eliminarq, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(borrar)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
        int clave;
        clave= Integer.parseInt(this.lbl_producto_eliminarq.getText());
        String cadenasql= "Delete from Productos where pd_clv="+clave;
        Properties datos =  new  Properties();
        String servidor;
        String driver;
        datos.put("user", "u7tuhhfbmthsu53c");
        datos.put("password", "Nw5nMTEHvX2U2r3gVAYj");
        servidor = "jdbc:mysql://bosgnclh26bmxuw456hf-mysql.services.clever-cloud.com:3306/bosgnclh26bmxuw456hf";
        driver = "com.mysql.jdbc.Driver";
        try {
            Class.forName(driver);
            Connection con = DriverManager.getConnection(servidor, datos);
            if (con != null) {
                
                System.out.println("elimino");
                Statement exe = con.createStatement();
                exe.execute(cadenasql);
                con.close();
                
                
            } else {
                System.out.println("No conecto");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            
            Logger.getLogger(Conexion.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog( this , "El valor fue eliminado correctamente" , "Eliminacion" , JOptionPane.INFORMATION_MESSAGE );
        eliminarTabla();
        llenarTabla();
    }//GEN-LAST:event_borrarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
            int renglon;
        DefaultTableModel modelo_tabla = (DefaultTableModel)this.jTable1.getModel();
        renglon = jTable1.getSelectedRow();
        this.lbl_producto_eliminarq.setText(""+modelo_tabla.getValueAt(renglon, 0));
        lbl_producto_eliminarq.setVisible(true);
        
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_producto_eliminarq;
    // End of variables declaration//GEN-END:variables
}
