/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;



import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author PRIV4
 */
public class Inventario extends javax.swing.JFrame {

    /**
     * Creates new form Inventario
     */
    public Inventario() throws ClassNotFoundException, SQLException {
        initComponents();
        
        String Cadena = "jdbc:mysql://127.0.0.1/boutique_accesorios_colibri";
        String Driver = "com.mysql.jdbc.Driver";
        String Usuario = "root";
        String Contraseña = "";

        int idinventario,existencia,cantidadvendida,idproducto,productos_idproducto;
        float preciocompra,precioventa;
        String nombre, descripcion,fecharegistro,categoria;
        
        
        
        
        String cadenasql;

        
        //cadenasql = "Select s.idproducto, s.nombre, s.preciocompra, s.descripcion, s.precioventa, s.existencia, s.fecharegistro, i.idinventario, i.cantidadvendida from inventarios i, productos s;";

        //cadenasql = "Select s.idproducto, s.nombre, s.preciocompra, s.descripcion, s.precioventa, s.existencia, s.fecharegistro, i.idinventario, i.cantidadvendida from inventarios i, productos s;";

        cadenasql = "SELECT *\n" +
"FROM productos\n" +
"INNER JOIN inventarios \n" +
"ON productos.idproducto = inventarios.productos_idproducto";
        System.out.println(cadenasql);
        ResultSet datos_productos;
        DefaultTableModel modelo_tabla = (DefaultTableModel) this.jTable1.getModel();
        try {
            Class.forName(Driver);//Utilizar un driver de tercero (el driver)
            java.sql.Connection con = DriverManager.getConnection(Cadena, Usuario, Contraseña);
            if (con != null) {
                System.out.println("conecto");
                Statement exe = con.createStatement();
                datos_productos = exe.executeQuery(cadenasql);
                while (datos_productos.next()) {
                    
                    //productos_idproducto = datos_productos.getInt("productos_idproducto");
                    
                    
                    idproducto = datos_productos.getInt("idproducto");
                    nombre = datos_productos.getString("nombre");
                    preciocompra = datos_productos.getFloat("preciocompra");
                    descripcion = datos_productos.getString("descripcion");
                    precioventa = datos_productos.getFloat("precioventa");
                    existencia = datos_productos.getInt("existencia");
                    fecharegistro = datos_productos.getString("fecharegistro");
                    idinventario = datos_productos.getInt("idinventario");
                    productos_idproducto = datos_productos.getInt("productos_idproducto");
                    cantidadvendida = datos_productos.getInt("cantidadvendida");
                    categoria = datos_productos.getString("categoria");
                    
                    Object vector[] = {idproducto,nombre,preciocompra,descripcion,precioventa,existencia,fecharegistro,idinventario, productos_idproducto, cantidadvendida,categoria};
                    modelo_tabla.addRow(vector);
                }
                con.close();
            } else {
                System.out.println("Error");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Conexion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Claves = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INVENTARIO");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Producto", "Nombre", "Precio Compra", "Descripcion", "Precio Venta", "Existencia", "Fecha Registro", "Id inventario", "productos_idproducto", "Cantidad Vendida", "categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido a inventario");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setOpaque(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/modificar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("id producto");

        jLabel3.setText("Nombre");

        jLabel4.setText("Precio Compra");

        Claves.setText("Claves:");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/echo.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Existencia");

        jLabel6.setText("Descripcion");

        jLabel7.setText("Precio Venta");

        jLabel8.setText("Id Inventario");

        jLabel9.setText("cantidad vendida");

        jLabel10.setText("Fecha Registro");

        jLabel11.setText("categoria");

        jLabel12.setText("producto_idproducto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel12)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(Claves)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Claves))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(1, 1, 1)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addGap(1, 1, 1)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addGap(1, 1, 1)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(115, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int renglon;
        
        DefaultTableModel modelo_tabla=(DefaultTableModel)this.jTable1.getModel();
        renglon = jTable1.getSelectedRow();
        //clave etiqueta
        int temp=(int)modelo_tabla.getValueAt(renglon, 0);
        
        //cajas
        //nombre
        String temp2 = modelo_tabla.getValueAt(renglon, 1).toString();

        float temp3 = (float)modelo_tabla.getValueAt(renglon, 2);
        String temp4 = modelo_tabla.getValueAt(renglon, 3).toString();
        float temp5 = (float)modelo_tabla.getValueAt(renglon, 4);
        int temp6 = (int)modelo_tabla.getValueAt(renglon, 5);
        String temp7 = modelo_tabla.getValueAt(renglon, 6).toString();
        int temp8 = (int)modelo_tabla.getValueAt(renglon, 7);
        int temp9 = (int)modelo_tabla.getValueAt(renglon, 9);
        String temp10 = modelo_tabla.getValueAt(renglon, 10).toString();
        int temp11 = (int)modelo_tabla.getValueAt(renglon, 8);
        
        this.Claves.setText("Clave: "+ modelo_tabla.getValueAt(renglon, 0));
        
        //idproducto int
        this.jTextField1.setText(Integer.toString(temp));
        temp=(int)modelo_tabla.getValueAt(renglon, 0);
//        //nombre string
        this.jTextField2.setText(temp2);
        temp2=modelo_tabla.getValueAt(renglon, 1).toString();
//        //precio compra float
        this.jTextField3.setText((Double.toString(temp3)));
        temp3=(float)modelo_tabla.getValueAt(renglon, 2);
//        //descripcion string
        this.jTextField4.setText(temp4);
        temp4=modelo_tabla.getValueAt(renglon, 3).toString();
//        //precio venta float
        this.jTextField5.setText((Double.toString(temp5)));
        temp5=(float)modelo_tabla.getValueAt(renglon, 4);
//        //existencia int
        this.jTextField6.setText(Integer.toString(temp6));
        temp6=(int)modelo_tabla.getValueAt(renglon, 5);
//        //fecha registro string
        this.jTextField7.setText(temp7);
        temp7=modelo_tabla.getValueAt(renglon, 6).toString();
//        //id inventario int
        this.jTextField8.setText(Integer.toString(temp8));
        temp8=(int)modelo_tabla.getValueAt(renglon, 7);
//        //cantidad vendida int
        this.jTextField9.setText(Integer.toString(temp9));
        temp9=(int)modelo_tabla.getValueAt(renglon, 8);
        //categoria
        this.jTextField10.setText((temp10));
        //temp10=modelo_tabla.getValueAt(renglon, 9).toString();
        this.jTextField11.setText(Integer.toString(temp11));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        

        DefaultTableModel modelo_tabla=(DefaultTableModel)this.jTable1.getModel();
        
        //UPDATE productos INNER JOIN inventarios SET productos.nombre = "a", productos.preciocompra = "10", productos.descripcion = "bai", productos.precioventa = "20", productos.existencia = "30", productos.fecharegistro = "2022/11/16", inventarios.productos_idproducto = "1", inventarios.cantidadvendida = "5" WHERE inventarios.productos_idproducto = inventarios.productos_idproducto;

//        int idproducto, existencia;
//        String nombre, descripcion, fecharegistro;
//        float preciocompra, precioventa;
//        
//        
//        int idinventario,productos_idproducto,cantidadvendida;
//        
//        int clave;
//        
//        
//        
//        clave=(int) modelo_tabla.getValueAt(jTable1.getSelectedRow(), 8);//id inventario
//        
//        idproducto = Integer.parseInt(this.jTextField1.getText());//id producto
//        nombre = this.jTextField2.getText();//nombre
//        preciocompra = Float.parseFloat(this.jTextField3.getText());
//        descripcion = this.jTextField4.getText();
//        precioventa = Float.parseFloat(this.jTextField5.getText());
//        existencia = Integer.parseInt(this.jTextField6.getText());
//        fecharegistro = this.jTextField7.getText();
//        idinventario = Integer.parseInt(this.jTextField8.getText());
//        
        
        
        
        
        
        
        int cantidadvendida,existencia,idproducto,idinventario,productos_idproducto;
        String nombre,descripcion,fecharegistro,categoria;
        float preciocompra,precioventa;
        
        int clv;
        
        clv=(int) modelo_tabla.getValueAt(jTable1.getSelectedRow(), 8);//etiqueta
        
        idinventario = Integer.parseInt(this.jTextField8.getText());
        nombre= (this.jTextField2.getText());
        preciocompra = Float.parseFloat(this.jTextField3.getText());//3
        descripcion = (this.jTextField4.getText());
        precioventa = Float.parseFloat(this.jTextField5.getText());//
        existencia = Integer.parseInt(this.jTextField6.getText());//6
        fecharegistro = this.jTextField7.getText();
        idproducto = Integer.parseInt(this.jTextField1.getText());
        cantidadvendida = Integer.parseInt(this.jTextField9.getText());
        categoria = this.jTextField10.getText();
        productos_idproducto = Integer.parseInt(this.jTextField11.getText());
        
        String Cadena = "jdbc:mysql://127.0.0.1/boutique_accesorios_colibri";
        String Driver = "com.mysql.jdbc.Driver";
        String Usuario = "root";
        String Contraseña = "";
        String cadenasql;

        cadenasql = "UPDATE productos INNER JOIN inventarios SET productos.nombre = '"+nombre+"', productos.preciocompra = '"+preciocompra+"', productos.descripcion = '"+descripcion+"', productos.precioventa = '"+precioventa+"', productos.existencia = '"+existencia+"', productos.fecharegistro = '"+fecharegistro+"', inventarios.productos_idproducto = '"+idproducto+"', inventarios.cantidadvendida = '"+cantidadvendida+"', productos.categoria = '"+categoria+"' WHERE inventarios.idinventario = "+idinventario+" AND productos.idproducto = "+idproducto;
        //cadenasql= "UPDATE `inventarios` SET `idinventario`='"+idinventario+"',`cantidadvendida`='"+cantidadvendida+"' WHERE `idinventario` ="+clv;
        System.out.println(cadenasql);
        ResultSet datos_productos;
        try {
                    Class.forName(Driver);//Utilizar un driver de tercero (el driver)
            java.sql.Connection con = DriverManager.getConnection(Cadena, Usuario, Contraseña);
                    if(con!= null)
                    {
                        System.out.println("Modificado");
                        Statement exe = con.createStatement();
                        exe.execute(cadenasql);
                        con.close();
                    }
                    else
                    {
                        System.out.println("Error");
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Conexion.class.getName()).log(Level.SEVERE, null, ex);
            }   catch (SQLException ex) {
                    Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PantallaPrincipal pan = new PantallaPrincipal();
        pan.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Inventario().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Inventario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Claves;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

}
